services:
    db:
      image: postgres:16
      restart: unless-stopped
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: heartmatch
      volumes:
        - db_data:/var/lib/postgresql/data
volumes:
    db_data: